#!/bin/bash

# Upload instances and features from Glyphs

family=Eczar
family2="Eczar"	# as used in Glyphs’ folder

# upload fonts from _instances folder to individual folders
cd $family

shopt -s nullglob

# OTFs from Glyphs
suf="otf"
for i in ../_instances/$family-*.$suf
do
	echo "Uploading $i"
	
	# copy _instance files to corresponding folders
	folder=`echo "$i" | sed -e "s/[^-]*-\([^-\.]*\)\.$suf/\1/"`
	if [[ ! -d $folder ]]; then mkdir $folder; fi
	rm $folder/font.$suf
	cp $i $folder/font.$suf
	
	# locate Glyphs’ Temp folder
	GlyphsTempFolder="/Users/davidbrezina/Library/Application Support/Glyphs/Temp"
	featuresfile=`echo "$GlyphsTempFolder/$family2-$folder/features" | sed -e "s/Italic/\ Italic/" | sed -e "s/-\ /-/"`
	# copy kerning from Glyphs’ Temp files
	subsetFeatureCode.py "$featuresfile" -L -f kern > $folder/kern.fea
	subsetFeatureCode.py "$featuresfile" -c kern > $folder/kernclasses.fea
	# copy mark and mkmk from Glyphs’ Temp files
	subsetFeatureCode.py "$featuresfile" -f mark > $folder/mark.fea
	subsetFeatureCode.py "$featuresfile" -f mkmk > $folder/mkmk.fea
	subsetFeatureCode.py "$featuresfile" -f abvm > $folder/abvm.fea
	subsetFeatureCode.py "$featuresfile" -f blwm > $folder/blwm.fea
	subsetFeatureCode.py "$featuresfile" -c mark > $folder/markclasses.fea
	# copy gdef table from Glyphs’ Temp files
	subsetFeatureCode.py "$featuresfile" -t gdef > $folder/gdef.fea
done

# TTFs from FontLab
suf="ttf"
for i in ../_instances/$family-*.$suf
do
	echo "Uploading $i"
	
	# copy _instance files to corresponding folders
	folder=`echo "$i" | sed -e "s/[^-]*-\([^-\.]*\)\.$suf/\1/"`
	if [[ ! -d $folder ]]; then mkdir $folder; fi
	rm $folder/font.$suf
	cp $i $folder/font.$suf
done
cd ..
